### ISSUE TITLE
Not an issue but a question about the project.

### ISSUE THREAD

**Issue by ytrezq** [gitpython-developers/gitdb#22] opened 2015-11-06 12:41 UTC
I currently have a valid git database, but due to a bug in`git-pack-objects`*(the process crash with a stack dump file)* I’m unable to pack the objects in a packfile with`git-repack`.

So Is there an example for the`write_pack()`function ?

**Comment by Byron** [comment] 2015-11-08 08:08
I am closing this issue as it seems to be a duplicate of the [respective question on stackoverflow](http://stackoverflow.com/questions/33565280/how-to-get-a-list-of-objects-in-a-variable-from-a-repository-path-in-gitpython).

**Closed by Byron** 2015-11-08 08:08 UTC

**Comment by ytrezq** [comment] 2015-11-08 17:45
@Byron : Yes, but it’s very unlikely someone with gitdb knowledge answer the question on so *(and you didn’t)*. at least it’s the so version that should be closed.

Adding examples or additional test cases *(since I’m just trying to achieve the same as the`git repack`command)* would enhance the project.
