### ISSUE TITLE
compat.py is missing and breaks "import git"

### ISSUE THREAD

**Issue by kdenney-rp** [gitpython-developers/gitdb#58] opened 2020-02-18 18:38 UTC
Dowloaded latest version 3.0.2
compat.py no longer exists.

Traceback:
File "/Users/kelly.denney/recoMD.datascience/tools/scorecards/followup_utils.py", line 1, in <module>
    import git
  File "/Users/kelly.denney/anaconda3/envs/recoMD-dev/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/Users/kelly.denney/anaconda3/envs/recoMD-dev/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/Users/kelly.denney/anaconda3/envs/recoMD-dev/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'

**Comment by Harmon758** [comment] 2020-02-18 18:39
Duplicate of https://github.com/gitpython-developers/GitPython/issues/983

**Closed by Harmon758** 2020-02-18 18:39 UTC
